- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Installs jail configs
  template:
    src: "generic.j2"
    dest: "/etc/fail2ban/jail.d/{{ item.key }}.conf"
    mode: 0640
    owner: root
  with_dict: "{{ f2b_jails }}"
  notify: Restart fail2ban

- name: Adds sudoers config for telegraf user
  template:
    src: fail2ban.sudoers.j2
    dest: /etc/sudoers.d/20_fail2ban
    mode: 0440
    owner: root
    group: root
  tags: ["sudo"]

