- name: Install fail2ban
  apt:
    name: fail2ban
    state: latest

- name: Installs jail configs
  template:
    src: "generic.j2"
    dest: "/etc/fail2ban/jail.d/{{ item.key }}.conf"
    mode: 0640
    owner: root
  with_dict: "{{ f2b_jails }}"
  notify: Restart fail2ban


